# Generated by Django 5.1.3 on 2025-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
