# Generated by Django 5.1.3 on 2025-02-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
